services:
  mariadb:
    container_name: 'mariadbd'
    build:
      context: /home/pjerddee/inception/srcs/requirements/mariadb/
    volumes:
      - database:/var/lib/mysql/
    networks:
      - docker-network
    env_file:
      - ./.env
    # ports:
    #   - "3306:3306"

volumes:
  database:
    name: database
    driver: local
    driver_opts:
      type: none
      o: "bind"
      device: /home/pjerddee/data/database/

networks:
  docker-network:
    name: docker-network