services:
  mariadb:
    container_name: 'mariadbd'
    build:
      context: /home/pjerddee/inception/srcs/requirements/mariadb/
      args:
        - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ADMIN=${MYSQL_ADMIN}
        - MYSQL_ADMIN_PASSWORD=${MYSQL_ADMIN_PASSWORD}
        - DB_NAME=${DB_NAME}
    volumes:
      - database:/var/lib/mysql/
    networks:
      - docker-network
  wordpress:
    container_name: 'wordpress'
    build:
      context: /home/pjerddee/inception/srcs/requirements/wordpress/
    networks:
      - docker-network
    env_file:
      - ./.env
    environment:
      - MYSQL_ADMIN=${MYSQL_ADMIN}
      - MYSQL_ADMIN_PASSWORD=${MYSQL_ADMIN_PASSWORD}
      - MYSQL_ADMIN_EMAIL=${MYSQL_ADMIN_EMAIL}
      - DB_NAME=${DB_NAME}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - BLOG_TITLE=${BLOG_TITLE}
      - HOST_NAME=${HOST_NAME}
    depends_on:
      - mariadb
    volumes:
      - wordpress:/public_html/blogdemo/
volumes:
  database:
    name: database
    driver: local
    driver_opts:
      type: none
      o: "bind"
      device: /home/pjerddee/data/database/
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: "bind"
      device: /home/pjerddee/data/wordpress/

networks:
  docker-network:
    name: docker-network