services:
  mariadb:
    container_name: 'mariadbd'
    build:
      context: /home/pjerddee/inception/srcs/requirements/mariadb/
    volumes:
      - database:/var/lib/mysql/
    networks:
      - docker-network
    env_file:
      - ./.env
  wordpress:
    container_name: 'wordpress'
    build:
      context: /home/pjerddee/inception/srcs/requirements/wordpress/
    networks:
      - docker-network
    env_file:
      - ./.env
    depends_on:
      - mariadb
volumes:
  database:
    name: database
    driver: local
    driver_opts:
      type: none
      o: "bind"
      device: /home/pjerddee/data/database/

networks:
  docker-network:
    name: docker-network