services:
  mariadb:
    image: mariadbd
    working_dir: /home/pjerddee/inception/srcs/requirements/mariadb/
    volumes: database:/var/lib/mysql
    networks: docker-network
    ports: 3306:3306

volumes:
  database:
    driver_opts:
        type: ""
        o: ""
        device: "/home/pjerddee/data/database"

networks:
  docker-network: