#!/bin/bash

service mariadb restart

#mysql_secure_installation << EOF
#
#n
#y
#$MYSQL_ROOT_PASSWORD
#$MYSQL_ROOT_PASSWORD
#y
#y
#y
#y
#EOF

mysql_secure_installation << EOF
$MYSQL_ROOT_PASSWORD
n
n
y
y
y
y
EOF

# Create user and grant privileges
mysql -u $MYSQL_ROOT_USER -p$MYSQL_ROOT_PASSWORD << EOF
ALTER USER '$MYSQL_ROOT_USER'@'localhost' IDENTIFIED BY '$MYSQL_ROOT_PASSWORD';
CREATE DATABASE IF NOT EXISTS $DB_NAME;
CREATE USER IF NOT EXISTS '$MYSQL_ADMIN'@'%' IDENTIFIED BY '$MYSQL_ADMIN_PASSWORD';
GRANT ALL PRIVILEGES ON *.* TO '$MYSQL_ADMIN'@'%';
CREATE USER IF NOT EXISTS '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, EXECUTE ON $DB_NAME.* TO '$MYSQL_USER'@'%';
GRANT SHOW DATABASES ON *.* TO '$MYSQL_USER'@'%';
GRANT USAGE ON *.* TO '$MYSQL_USER'@'%';
FLUSH PRIVILEGES;
EOF

service mariadb restart

chown -R mysql:mysql /var/lib/mysql
chmod -R 777 /var/lib/mysql
